apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: port-ops-demo
  labels:
    app.kubernetes.io/name: port-ops-demo
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: port-ops-demo
spec:
  selector:
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
