apiVersion: v1
kind: Service
metadata:
  name: container-service
  namespace: port-ops-demo
  labels:
    app.kubernetes.io/name: port-ops-demo
    app.kubernetes.io/component: container-service
    app.kubernetes.io/part-of: port-ops-demo
spec:
  selector:
    app.kubernetes.io/component: container-service
  ports:
    - name: http
      port: 9082
      targetPort: 9082
  type: ClusterIP
