apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/part-of: port-ops-demo
    includeSelectors: false

# Override namespace at overlay level for clarity
namespace: port-ops-demo
