apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: port-ops-demo
  labels:
    app.kubernetes.io/name: port-ops-demo
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: port-ops-demo
spec:
  selector:
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  type: ClusterIP
