apiVersion: v1
kind: Service
metadata:
  name: vessel-service
  namespace: port-ops-demo
  labels:
    app.kubernetes.io/name: port-ops-demo
    app.kubernetes.io/component: vessel-service
    app.kubernetes.io/part-of: port-ops-demo
spec:
  selector:
    app.kubernetes.io/component: vessel-service
  ports:
    - name: http
      port: 9081
      targetPort: 9081
  type: ClusterIP
