apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-kubeconfig
  namespace: {{ .Release.Namespace }}
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        server: {{ .Values.customKubeconfig.server | default "https://kubernetes.default.svc" | quote }}
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      name: {{ .Values.customKubeconfig.cluster }}
    contexts:
    - context:
        cluster: {{ .Values.customKubeconfig.cluster | default "psr-cluster" | quote }}
        user: {{ .Values.customKubeconfig.user }}
      name: psr-context
    current-context: psr-context
    kind: Config
    preferences: {}
    users:
    - name: {{ .Values.customKubeconfig.user | default "psr-user" | quote }}
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token