{{- $secret := (lookup "v1" "Secret" .Release.Namespace "cluster-agent-secret") }}
  {{- $annotations := dict "temp" "temp" }}
  {{- $accessKeyMissing := not .Values.controllerInfo.accessKey }}
  {{- if $secret }}
  {{- $annotations = $secret.metadata.annotations }}
  {{- end }}

  {{- if or (not $secret) (get $annotations "appdynamics.helm.charts/created-by") }}
  {{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-secret
  namespace: {{ $namespace }}
  annotations:
    appdynamics.helm.charts/created-by: cluster-agent-helm-chart
type: Opaque
data:
  {{- with .Values.controllerInfo -}}
    {{- if .accessKey }}
    controller-key: {{ include "sensitiveData" (dict "data" .accessKey) }}
    {{- end -}}
    {{- end -}}
    {{- if .Values.instrumentationConfig.enabled -}}
    {{- with .Values.controllerInfo }}
    {{- if and .username .password }}
    api-user: {{ cat (.username | trim ) "@" (.account | trim ) ":" (.password | trim ) | nospace | b64enc -}}
    {{- end -}}
    {{- end -}}
    {{- end -}}
  {{- end -}}
