apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: port-ops-demo
  labels:
    app.kubernetes.io/name: port-ops-demo
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: port-ops-demo
spec:
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
